### ISSUE TITLE
Error that halts final thickness calculation

### ISSUE THREAD

**Issue by JonathanAMichaels** [Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension#2]
In BoneThicknessMapping.py, line 931
`return thicknessTableNode, airCellTable`
should be
`return thicknessTableNode, airCellTableNode`

**Comment by e-simpson** [comment]
Fixed.
Thanks for pointing this out @JonathanAMichaels! The fix should appear in the next nightly build of 3D Slicer.
