### ISSUE TITLE
Can't get it to display result using recent nighly build

### ISSUE THREAD

**Issue by w1ebr** [Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension#3]
When I apply the extension to a volume from a ct scan of a cranium everything is colored yellow. I also don't see a slider which is mentioned in the documentation. How do I try to solve my problem?
Thank you.
![All_yellow](https://user-images.githubusercontent.com/22258917/122698090-9ff8e580-d214-11eb-9748-1e2705bc0430.png)

Gene Risi

**Comment by e-simpson** [comment]
Hi Gene Risi (@w1ebr), thanks for your interest in the module.

I downloaded and tested this on the latest Slicer Nightly/Preview release: version 4.13.0 revision 29995 (built 2021-06-23) and it worked well on my end. Here's an image of the output using the "CBCTDentalSurgery" sample dataset's PreDentalSurgery volume with the following BoneThicknessMapping configuration changes: Anterior cast direction and extreme render quality:
![image](https://user-images.githubusercontent.com/25159851/123146785-48cd5d80-d42c-11eb-9064-ee8c36bca6c0.png)

The yellow overlay your seeing there tells me the initial mapping ray-cast is complete and that the secondary thickness ray-cast hasn't applied it's thickness colour values. I would recommend trying to reinstall the new Slicer Nightly/Preview or checking the 3D Slicer Python Interactor window for error codes.

If by slider you mean the to the Otsu threshold range slider. This is found within the Segmentation Editor extension. You'll want to select an input volume then scroll down to the Effects section and select the Threshold tool. This slider will help recommend valid Otsu ranges that can be set in the BoneThicknessMapping configuration. 

Evan

**Comment by e-simpson** [comment]
Closing. Please reopen if issues remain.
